<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Batch extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Batch_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'batch/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'batch/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'batch/index.html';
            $config['first_url'] = base_url() . 'batch/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Batch_model->total_rows($q);
        $batch = $this->Batch_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'batch_data' => $batch,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
            'judul_page' => 'Batch Soal',
            'konten' => 'batch/batch_list',
        );
        $this->load->view('v_index', $data);
    }

    public function read($id) 
    {
        $row = $this->Batch_model->get_by_id($id);
        if ($row) {
            $data = array(
		'batch_id' => $row->batch_id,
		'nama_batch' => $row->nama_batch,
	    );
            $this->load->view('batch/batch_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('batch'));
        }
    }

    public function create() 
    {
        $data = array(
            'judul_page' => 'Batch Soal',
            'konten' => 'batch/batch_form',
            'button' => 'Create',
            'action' => site_url('batch/create_action'),
	    'batch_id' => set_value('batch_id'),
	    'nama_batch' => set_value('nama_batch'),
	);
        $this->load->view('v_index', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_batch' => $this->input->post('nama_batch',TRUE),
	    );

            $this->Batch_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('batch'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Batch_model->get_by_id($id);

        if ($row) {
            $data = array(
                'judul_page' => 'Batch Soal',
                'konten' => 'batch/batch_form',
                'button' => 'Update',
                'action' => site_url('batch/update_action'),
		'batch_id' => set_value('batch_id', $row->batch_id),
		'nama_batch' => set_value('nama_batch', $row->nama_batch),
	    );
            $this->load->view(v_index, $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('batch'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('batch_id', TRUE));
        } else {
            $data = array(
		'nama_batch' => $this->input->post('nama_batch',TRUE),
	    );

            $this->Batch_model->update($this->input->post('batch_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('batch'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Batch_model->get_by_id($id);

        if ($row) {
            $this->Batch_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('batch'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('batch'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_batch', 'nama batch', 'trim|required');

	$this->form_validation->set_rules('batch_id', 'batch_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Batch.php */
/* Location: ./application/controllers/Batch.php */
/* Please DO NOT modify this information : */
/* Generated by Boy Kurniawan 2019-10-05 15:51:09 */
/* https://jualkoding.com */